import { PcfComponent } from '@gtui/gt-ui-framework';
import { PcfTextInput } from '@gtui/gt-ui-framework';
import { PcfButton } from '@gtui/gt-ui-framework';
import { PcfListView } from '@gtui/gt-ui-framework';

export class APDProductManagementPage {
	aPDGenerateProductToolbarButtonSetGenerate = PcfButton('#APDProductManagementPage-APDGenerateProductToolbarButtonSet-Generate');
	generateGenerateAPIAllMenuItem = PcfComponent('#APDProductManagementPage-APDGenerateProductToolbarButtonSet-Generate-GenerateAPIAllMenuItem');
	generateAPIAllMenuItemGenerateAPICodeMenuItem = PcfComponent('#APDProductManagementPage-APDGenerateProductToolbarButtonSet-Generate-GenerateAPIAllMenuItem-GenerateAPICodeMenuItem');
	generateAPIAllMenuItemGenerateAPITestsMenuItem = PcfComponent('#APDProductManagementPage-APDGenerateProductToolbarButtonSet-Generate-GenerateAPIAllMenuItem-GenerateAPITestsMenuItem');
	generateGenerateAllMenuItem = PcfComponent('#APDProductManagementPage-APDGenerateProductToolbarButtonSet-Generate-GenerateAllMenuItem');
	generateGenerateBaseCodeMenuItem = PcfComponent('#APDProductManagementPage-APDGenerateProductToolbarButtonSet-Generate-GenerateBaseCodeMenuItem');
	generateGenerateExternalMenuItem = PcfComponent('#APDProductManagementPage-APDGenerateProductToolbarButtonSet-Generate-GenerateExternalMenuItem');
	aPDInstalledEditionsPanelRowActivatedEditionLV = PcfListView('#APDProductManagementPage-APDInstalledEditionsPanelRow-ActivatedEditionLV');
	aPDInstalledEditionsPanelRowInvalidActivatedEditionsRulesLV = PcfListView('#APDProductManagementPage-APDInstalledEditionsPanelRow-InvalidActivatedEditionsRulesLV');
	aPDInstalledEditionsPanelRowInvalidEditionsRulesLV = PcfListView('#APDProductManagementPage-APDInstalledEditionsPanelRow-InvalidEditionsRulesLV');
	aPDInstalledEditionsPanelRowPreloadedEditionLV = PcfListView('#APDProductManagementPage-APDInstalledEditionsPanelRow-PreloadedEditionLV');
	aPDProductManagementPageAPDProductManagementPage_UpLink = PcfButton('#APDProductManagementPage-APDProductManagementPage_UpLink');
	aPDProductManagementPageActivateEditions = PcfButton('#APDProductManagementPage-ActivateEditions');
	aPDProductManagementPageEditProduct = PcfButton('#APDProductManagementPage-EditProduct');
	aPDProductManagementPageExportGeneratedTemplate = PcfButton('#APDProductManagementPage-ExportGeneratedTemplate');
	aPDProductManagementPageExportTemplate = PcfButton('#APDProductManagementPage-ExportTemplate');
	aPDProductManagementPageGenerateTemplate = PcfButton('#APDProductManagementPage-GenerateTemplate');
	aPDProductManagementPageInstalledProductLV = PcfListView('#APDProductManagementPage-InstalledProductLV');
	aPDProductManagementPageInstalledProductsTab = PcfButton('#APDProductManagementPage-InstalledProductsTab');
	aPDProductManagementPageManualProductLV = PcfListView('#APDProductManagementPage-ManualProductLV');
	manualProductLV_tbImportFromCloud = PcfButton('#APDProductManagementPage-ManualProductLV_tb-ImportFromCloud');
	manualProductLV_tbImportFromTemplate = PcfButton('#APDProductManagementPage-ManualProductLV_tb-ImportFromTemplate');
	manualProductLV_tbImportFromXmind = PcfButton('#APDProductManagementPage-ManualProductLV_tb-ImportFromXmind');
	manualProductLV_tbNewProduct = PcfButton('#APDProductManagementPage-ManualProductLV_tb-NewProduct');
	manualProductLV_tbSyncWithCloud = PcfButton('#APDProductManagementPage-ManualProductLV_tb-SyncWithCloud');
	aPDProductManagementPagePreloadEditions = PcfButton('#APDProductManagementPage-PreloadEditions');
	aPDProductManagementPageProductDetailsAbbreviation = PcfTextInput('#APDProductManagementPage-ProductDetailsAbbreviation');
	aPDProductManagementPageProductDetailsDescription = PcfTextInput('#APDProductManagementPage-ProductDetailsDescription');
	aPDProductManagementPageProductDetailsIdentifier = PcfTextInput('#APDProductManagementPage-ProductDetailsIdentifier');
	aPDProductManagementPageProductDetailsName = PcfTextInput('#APDProductManagementPage-ProductDetailsName');
	aPDProductManagementPageProductDetailsTab = PcfButton('#APDProductManagementPage-ProductDetailsTab');
	aPDProductManagementPageProductInstalledEditionsTab = PcfButton('#APDProductManagementPage-ProductInstalledEditionsTab');
	aPDProductManagementPageProductSubmissionsLV = PcfListView('#APDProductManagementPage-ProductSubmissionsLV');
	aPDProductManagementPageProductSubmissionsTab = PcfButton('#APDProductManagementPage-ProductSubmissionsTab');
	aPDProductManagementPageProductTreeLV = PcfListView('#APDProductManagementPage-ProductTreeLV');
	productTreeLV_tbCollapseAll = PcfButton('#APDProductManagementPage-ProductTreeLV_tb-CollapseAll');
	productTreeLV_tbExpandAll = PcfButton('#APDProductManagementPage-ProductTreeLV_tb-ExpandAll');
	productTreeLV_tbTreeContents = PcfTextInput('#APDProductManagementPage-ProductTreeLV_tb-TreeContents');
	aPDProductManagementPageRemoveProduct = PcfButton('#APDProductManagementPage-RemoveProduct');
	aPDProductManagementPageUpdateProductButton = PcfButton('#APDProductManagementPage-UpdateProductButton');
	updateProductButtonFromCloud = PcfButton('#APDProductManagementPage-UpdateProductButton-FromCloud');
	updateProductButtonFromTemplate = PcfButton('#APDProductManagementPage-UpdateProductButton-FromTemplate');
	updateProductButtonFromXmind = PcfButton('#APDProductManagementPage-UpdateProductButton-FromXmind');
	aPDProductManagementPageVisualizedProductsTab = PcfButton('#APDProductManagementPage-VisualizedProductsTab');
	aPDProductManagementPage_Paging = PcfButton('#APDProductManagementPage-_Paging');
	aPDProductManagementPage__crumb__ = PcfComponent('#APDProductManagementPage-__crumb__');
	aPDProductManagementPage_msgs = PcfButton('#APDProductManagementPage-_msgs');
	aPDProductManagementPageselectedProductTab = PcfButton('#APDProductManagementPage-selectedProductTab');
}
