import { PcfComponent } from '@gtui/gt-ui-framework';
import { PcfTextInput } from '@gtui/gt-ui-framework';
import { PcfDateValueInput } from '@gtui/gt-ui-framework';
import { PcfSelectInput } from '@gtui/gt-ui-framework';
import { PcfButton } from '@gtui/gt-ui-framework';

export class DriverMVRInfoPopup {
	driverMVRInfoPopupDriverMVRInfoPopup_UpLink = PcfButton('#DriverMVRInfoPopup-DriverMVRInfoPopup_UpLink');
	mVRListAdditionalInfoTab = PcfButton('#DriverMVRInfoPopup-MVRList-AdditionalInfoTab');
	mVRListDriverCardTab = PcfButton('#DriverMVRInfoPopup-MVRList-DriverCardTab');
	mVRListIncidentsTab = PcfButton('#DriverMVRInfoPopup-MVRList-IncidentsTab');
	mVRDriverDVAddress = PcfTextInput('#DriverMVRInfoPopup-MVRList-MVRDriverDV-Address');
	mVRDriverDVDOB = PcfDateValueInput('#DriverMVRInfoPopup-MVRList-MVRDriverDV-DOB');
	mVRDriverDVDonor = PcfComponent('#DriverMVRInfoPopup-MVRList-MVRDriverDV-Donor');
	mVRDriverDVEyes = PcfTextInput('#DriverMVRInfoPopup-MVRList-MVRDriverDV-Eyes');
	mVRDriverDVGender = PcfSelectInput('#DriverMVRInfoPopup-MVRList-MVRDriverDV-Gender');
	driverMVRInfoPopupMVRListMVRDriverDVGlobalPersonNameInputSetFirstName = PcfTextInput('#DriverMVRInfoPopup-MVRList-MVRDriverDV-GlobalPersonNameInputSet-FirstName');
	driverMVRInfoPopupMVRListMVRDriverDVGlobalPersonNameInputSetFirstNameKanji = PcfTextInput('#DriverMVRInfoPopup-MVRList-MVRDriverDV-GlobalPersonNameInputSet-FirstNameKanji');
	driverMVRInfoPopupMVRListMVRDriverDVGlobalPersonNameInputSetLastName = PcfTextInput('#DriverMVRInfoPopup-MVRList-MVRDriverDV-GlobalPersonNameInputSet-LastName');
	driverMVRInfoPopupMVRListMVRDriverDVGlobalPersonNameInputSetLastNameKanji = PcfTextInput('#DriverMVRInfoPopup-MVRList-MVRDriverDV-GlobalPersonNameInputSet-LastNameKanji');
	driverMVRInfoPopupMVRListMVRDriverDVGlobalPersonNameInputSetNameSummary = PcfTextInput('#DriverMVRInfoPopup-MVRList-MVRDriverDV-GlobalPersonNameInputSet-NameSummary');
	driverMVRInfoPopupMVRListMVRDriverDVGlobalPersonNameInputSetMiddleName = PcfTextInput('#DriverMVRInfoPopup-MVRList-MVRDriverDV-GlobalPersonNameInputSet-MiddleName');
	driverMVRInfoPopupMVRListMVRDriverDVGlobalPersonNameInputSetParticle = PcfTextInput('#DriverMVRInfoPopup-MVRList-MVRDriverDV-GlobalPersonNameInputSet-Particle');
	driverMVRInfoPopupMVRListMVRDriverDVGlobalPersonNameInputSetPrefix = PcfSelectInput('#DriverMVRInfoPopup-MVRList-MVRDriverDV-GlobalPersonNameInputSet-Prefix');
	driverMVRInfoPopupMVRListMVRDriverDVGlobalPersonNameInputSetSuffix = PcfSelectInput('#DriverMVRInfoPopup-MVRList-MVRDriverDV-GlobalPersonNameInputSet-Suffix');
	mVRDriverDVHair = PcfTextInput('#DriverMVRInfoPopup-MVRList-MVRDriverDV-Hair');
	mVRDriverDVHeight = PcfTextInput('#DriverMVRInfoPopup-MVRList-MVRDriverDV-Height');
	mVRDriverDVRace = PcfTextInput('#DriverMVRInfoPopup-MVRList-MVRDriverDV-Race');
	mVRDriverDVSSN = PcfTextInput('#DriverMVRInfoPopup-MVRList-MVRDriverDV-SSN');
	mVRDriverDVWeight = PcfTextInput('#DriverMVRInfoPopup-MVRList-MVRDriverDV-Weight');
	mVRIncidentLDVCodeHeader = PcfButton('#DriverMVRInfoPopup-MVRList-MVRIncidentLDV-CodeHeader');
	mVRIncidentLDVConvictionDateHeader = PcfButton('#DriverMVRInfoPopup-MVRList-MVRIncidentLDV-ConvictionDateHeader');
	mVRIncidentLDVDescriptionHeader = PcfButton('#DriverMVRInfoPopup-MVRList-MVRIncidentLDV-DescriptionHeader');
	mVRIncidentLDVIncidentAccidentInvolved = PcfTextInput('#DriverMVRInfoPopup-MVRList-MVRIncidentLDV-IncidentAccidentInvolved');
	mVRIncidentLDVIncidentCode = PcfTextInput('#DriverMVRInfoPopup-MVRList-MVRIncidentLDV-IncidentCode');
	mVRIncidentLDVIncidentConvReinDate = PcfDateValueInput('#DriverMVRInfoPopup-MVRList-MVRIncidentLDV-IncidentConvReinDate');
	mVRIncidentLDVIncidentCourt = PcfTextInput('#DriverMVRInfoPopup-MVRList-MVRIncidentLDV-IncidentCourt');
	mVRIncidentLDVIncidentDescription = PcfTextInput('#DriverMVRInfoPopup-MVRList-MVRIncidentLDV-IncidentDescription');
	mVRIncidentLDVIncidentDisposition = PcfTextInput('#DriverMVRInfoPopup-MVRList-MVRIncidentLDV-IncidentDisposition');
	mVRIncidentLDVIncidentEligibleDate = PcfDateValueInput('#DriverMVRInfoPopup-MVRList-MVRIncidentLDV-IncidentEligibleDate');
	mVRIncidentLDVIncidentLocation = PcfTextInput('#DriverMVRInfoPopup-MVRList-MVRIncidentLDV-IncidentLocation');
	mVRIncidentLDVIncidentPoints = PcfTextInput('#DriverMVRInfoPopup-MVRList-MVRIncidentLDV-IncidentPoints');
	mVRIncidentLDVIncidentSpeedZone = PcfTextInput('#DriverMVRInfoPopup-MVRList-MVRIncidentLDV-IncidentSpeedZone');
	mVRIncidentLDVIncidentState = PcfTextInput('#DriverMVRInfoPopup-MVRList-MVRIncidentLDV-IncidentState');
	mVRIncidentLDVIncidentStateCode = PcfTextInput('#DriverMVRInfoPopup-MVRList-MVRIncidentLDV-IncidentStateCode');
	mVRIncidentLDVIncidentType = PcfSelectInput('#DriverMVRInfoPopup-MVRList-MVRIncidentLDV-IncidentType');
	mVRIncidentLDVIncidentVehicleSpeed = PcfTextInput('#DriverMVRInfoPopup-MVRList-MVRIncidentLDV-IncidentVehicleSpeed');
	mVRIncidentLDVIncidentViolDate = PcfDateValueInput('#DriverMVRInfoPopup-MVRList-MVRIncidentLDV-IncidentViolDate');
	mVRIncidentLDVIncidentViolationNumber = PcfTextInput('#DriverMVRInfoPopup-MVRList-MVRIncidentLDV-IncidentViolationNumber');
	mVRIncidentLDVLocationHeader = PcfButton('#DriverMVRInfoPopup-MVRList-MVRIncidentLDV-LocationHeader');
	mVRIncidentLDVMVRIncidentCardTab = PcfButton('#DriverMVRInfoPopup-MVRList-MVRIncidentLDV-MVRIncidentCardTab');
	mVRIncidentLDVPointsHeader = PcfButton('#DriverMVRInfoPopup-MVRList-MVRIncidentLDV-PointsHeader');
	mVRIncidentLDVRecordTypeHeader = PcfButton('#DriverMVRInfoPopup-MVRList-MVRIncidentLDV-RecordTypeHeader');
	mVRIncidentLDVViolationDateHeader = PcfButton('#DriverMVRInfoPopup-MVRList-MVRIncidentLDV-ViolationDateHeader');
	mVRListReportDateHeader = PcfButton('#DriverMVRInfoPopup-MVRList-ReportDateHeader');
	mVRListRequestedDateHeader = PcfButton('#DriverMVRInfoPopup-MVRList-RequestedDateHeader');
	mVRListYearsRequestedHeader = PcfButton('#DriverMVRInfoPopup-MVRList-YearsRequestedHeader');
	mVRList_ListPaging = PcfButton('#DriverMVRInfoPopup-MVRList-_ListPaging');
	driverMVRInfoPopup_Paging = PcfButton('#DriverMVRInfoPopup-_Paging');
	driverMVRInfoPopup__crumb__ = PcfComponent('#DriverMVRInfoPopup-__crumb__');
	driverMVRInfoPopup_msgs = PcfButton('#DriverMVRInfoPopup-_msgs');
}
