import { PcfComponent } from '@gtui/gt-ui-framework';
import { PcfTextInput } from '@gtui/gt-ui-framework';
import { PcfSelectInput } from '@gtui/gt-ui-framework';
import { PcfButton } from '@gtui/gt-ui-framework';
import { PcfListView } from '@gtui/gt-ui-framework';

export class BAVehiclePopup {
	bAVehiclePopupBAVehiclePopup_UpLink = PcfButton('#BAVehiclePopup-BAVehiclePopup_UpLink');
	bAVehicleCVAdditionalCoveragesCardTab = PcfButton('#BAVehiclePopup-VehicleScreen-BAVehicleCV-AdditionalCoveragesCardTab');
	bAVehiclePopupVehicleScreenBAVehicleCVAdditionalCoveragesPanelSetAdditionalCoveragesDV_tbAdd = PcfButton('#BAVehiclePopup-VehicleScreen-BAVehicleCV-AdditionalCoveragesPanelSet-AdditionalCoveragesDV_tb-Add');
	bAVehiclePopupVehicleScreenBAVehicleCVAdditionalInterestDetailsDVAdditionalInterestLV = PcfListView('#BAVehiclePopup-VehicleScreen-BAVehicleCV-AdditionalInterestDetailsDV-AdditionalInterestLV');
	bAVehiclePopupVehicleScreenBAVehicleCVAdditionalInterestDetailsDVAdditionalInterestLV_tbAdd = PcfButton('#BAVehiclePopup-VehicleScreen-BAVehicleCV-AdditionalInterestDetailsDV-AdditionalInterestLV_tb-Add');
	bAVehiclePopupVehicleScreenBAVehicleCVAdditionalInterestDetailsDVAdditionalInterestLV_tbAddContactsButton = PcfButton('#BAVehiclePopup-VehicleScreen-BAVehicleCV-AdditionalInterestDetailsDV-AdditionalInterestLV_tb-AddContactsButton');
	bAVehiclePopupVehicleScreenBAVehicleCVAdditionalInterestDetailsDVAdditionalInterestLV_tbAddContactsButtonAddExistingContact = PcfButton('#BAVehiclePopup-VehicleScreen-BAVehicleCV-AdditionalInterestDetailsDV-AdditionalInterestLV_tb-AddContactsButton-AddExistingContact');
	bAVehiclePopupVehicleScreenBAVehicleCVAdditionalInterestDetailsDVAdditionalInterestLV_tbAddContactsButtonAddFromSearch = PcfButton('#BAVehiclePopup-VehicleScreen-BAVehicleCV-AdditionalInterestDetailsDV-AdditionalInterestLV_tb-AddContactsButton-AddFromSearch');
	bAVehiclePopupVehicleScreenBAVehicleCVAdditionalInterestDetailsDVAdditionalInterestLV_tbAddContactsButtonAddOtherContact = PcfButton('#BAVehiclePopup-VehicleScreen-BAVehicleCV-AdditionalInterestDetailsDV-AdditionalInterestLV_tb-AddContactsButton-AddOtherContact');
	bAVehiclePopupVehicleScreenBAVehicleCVAdditionalInterestDetailsDVAdditionalInterestLV_tbRemove = PcfButton('#BAVehiclePopup-VehicleScreen-BAVehicleCV-AdditionalInterestDetailsDV-AdditionalInterestLV_tb-Remove');
	bAGarageLocationInputEditGarageLocation = PcfButton('#BAVehiclePopup-VehicleScreen-BAVehicleCV-BAGarageLocationInputSet-BAGarageLocationInput-EditGarageLocation');
	bAGarageLocationInputNewGarageLocation = PcfButton('#BAVehiclePopup-VehicleScreen-BAVehicleCV-BAGarageLocationInputSet-BAGarageLocationInput-NewGarageLocation');
	bAVehicleCVCoveragesCardTab = PcfButton('#BAVehiclePopup-VehicleScreen-BAVehicleCV-CoveragesCardTab');
	vehicleDVBodyType = PcfSelectInput('#BAVehiclePopup-VehicleScreen-BAVehicleCV-VehicleDV-BodyType');
	classCodeSelectClassCode = PcfButton('#BAVehiclePopup-VehicleScreen-BAVehicleCV-VehicleDV-ClassCode-SelectClassCode');
	vehicleDVColor = PcfTextInput('#BAVehiclePopup-VehicleScreen-BAVehicleCV-VehicleDV-Color');
	vehicleDVCost = PcfTextInput('#BAVehiclePopup-VehicleScreen-BAVehicleCV-VehicleDV-Cost');
	vehicleDVDestinationZone = PcfSelectInput('#BAVehiclePopup-VehicleScreen-BAVehicleCV-VehicleDV-DestinationZone');
	vehicleDVLeaseOrRent = PcfComponent('#BAVehiclePopup-VehicleScreen-BAVehicleCV-VehicleDV-LeaseOrRent');
	vehicleDVLengthOfLease = PcfSelectInput('#BAVehiclePopup-VehicleScreen-BAVehicleCV-VehicleDV-LengthOfLease');
	vehicleDVLicensePlate = PcfTextInput('#BAVehiclePopup-VehicleScreen-BAVehicleCV-VehicleDV-LicensePlate');
	vehicleDVLicenseState = PcfSelectInput('#BAVehiclePopup-VehicleScreen-BAVehicleCV-VehicleDV-LicenseState');
	vehicleDVMake = PcfTextInput('#BAVehiclePopup-VehicleScreen-BAVehicleCV-VehicleDV-Make');
	vehicleDVModel = PcfTextInput('#BAVehiclePopup-VehicleScreen-BAVehicleCV-VehicleDV-Model');
	vehicleDVOriginationZone = PcfSelectInput('#BAVehiclePopup-VehicleScreen-BAVehicleCV-VehicleDV-OriginationZone');
	vehicleDVStatedValue = PcfTextInput('#BAVehiclePopup-VehicleScreen-BAVehicleCV-VehicleDV-StatedValue');
	vehicleDVType = PcfSelectInput('#BAVehiclePopup-VehicleScreen-BAVehicleCV-VehicleDV-Type');
	vehicleDVVehicleCond = PcfComponent('#BAVehiclePopup-VehicleScreen-BAVehicleCV-VehicleDV-VehicleCond');
	vehicleDVVehicleNumber = PcfTextInput('#BAVehiclePopup-VehicleScreen-BAVehicleCV-VehicleDV-VehicleNumber');
	vehicleDVVin = PcfTextInput('#BAVehiclePopup-VehicleScreen-BAVehicleCV-VehicleDV-Vin');
	vehicleDVYear = PcfTextInput('#BAVehiclePopup-VehicleScreen-BAVehicleCV-VehicleDV-Year');
	vehicleDVYearPurchased = PcfTextInput('#BAVehiclePopup-VehicleScreen-BAVehicleCV-VehicleDV-YearPurchased');
	bAVehicleCVVehicleDetailCardTab = PcfButton('#BAVehiclePopup-VehicleScreen-BAVehicleCV-VehicleDetailCardTab');
	vehicleScreenCancel = PcfButton('#BAVehiclePopup-VehicleScreen-Cancel');
	vehicleScreenEdit = PcfButton('#BAVehiclePopup-VehicleScreen-Edit');
	bAVehiclePopupVehicleScreenPreferredCoverageCurrencySelectorRefPreferredCoverageCurrencyPanelSetCoverageCurrencyDisplay = PcfTextInput('#BAVehiclePopup-VehicleScreen-PreferredCoverageCurrencySelectorRef-PreferredCoverageCurrencyPanelSet-CoverageCurrencyDisplay');
	bAVehiclePopupVehicleScreenPreferredCoverageCurrencySelectorRefPreferredCoverageCurrencyPanelSetPreferredCoverageCurrencySelectorDropDown = PcfSelectInput('#BAVehiclePopup-VehicleScreen-PreferredCoverageCurrencySelectorRef-PreferredCoverageCurrencyPanelSet-PreferredCoverageCurrencySelectorDropDown');
	vehicleScreenUpdate = PcfButton('#BAVehiclePopup-VehicleScreen-Update');
	vehicleScreen_msgs = PcfButton('#BAVehiclePopup-VehicleScreen-_msgs');
	bAVehiclePopup_Paging = PcfButton('#BAVehiclePopup-_Paging');
	bAVehiclePopup__crumb__ = PcfComponent('#BAVehiclePopup-__crumb__');
}
