import { PcfComponent } from '@gtui/gt-ui-framework';
import { PcfButton } from '@gtui/gt-ui-framework';
import { PcfListView } from '@gtui/gt-ui-framework';

export class TroubleTicketTransactionsPopup {
	troubleTicketTransactionsPopupTroubleTicketTransactionsPopup_UpLink = PcfButton('#TroubleTicketTransactionsPopup-TroubleTicketTransactionsPopup_UpLink');
	troubleTicketsTransactionsScreenCancel = PcfButton('#TroubleTicketTransactionsPopup-TroubleTicketsTransactionsScreen-Cancel');
	troubleTicketsTransactionsScreenEdit = PcfButton('#TroubleTicketTransactionsPopup-TroubleTicketsTransactionsScreen-Edit');
	troubleTicketTransactionsPopupTroubleTicketsTransactionsScreenTroubleTicketRelatedTransactionsDVTroubleTicketTransactionsLV = PcfListView('#TroubleTicketTransactionsPopup-TroubleTicketsTransactionsScreen-TroubleTicketRelatedTransactionsDV-TroubleTicketTransactionsLV');
	troubleTicketTransactionsPopupTroubleTicketsTransactionsScreenTroubleTicketRelatedTransactionsDVTroubleTicketTransactionsLV_tbTroubleTicketRelatedTransactionsDV_AddButton = PcfButton('#TroubleTicketTransactionsPopup-TroubleTicketsTransactionsScreen-TroubleTicketRelatedTransactionsDV-TroubleTicketTransactionsLV_tb-TroubleTicketRelatedTransactionsDV_AddButton');
	troubleTicketTransactionsPopupTroubleTicketsTransactionsScreenTroubleTicketRelatedTransactionsDVTroubleTicketTransactionsLV_tbTroubleTicketRelatedTransactionsDV_RemoveButton = PcfButton('#TroubleTicketTransactionsPopup-TroubleTicketsTransactionsScreen-TroubleTicketRelatedTransactionsDV-TroubleTicketTransactionsLV_tb-TroubleTicketRelatedTransactionsDV_RemoveButton');
	troubleTicketTransactionsPopupTroubleTicketsTransactionsScreenTroubleTicketRelatedTransactionsDVTroubleTicketTransactionsLV_tbtransactions = PcfButton('#TroubleTicketTransactionsPopup-TroubleTicketsTransactionsScreen-TroubleTicketRelatedTransactionsDV-TroubleTicketTransactionsLV_tb-transactions');
	troubleTicketsTransactionsScreenUpdate = PcfButton('#TroubleTicketTransactionsPopup-TroubleTicketsTransactionsScreen-Update');
	troubleTicketsTransactionsScreen_msgs = PcfButton('#TroubleTicketTransactionsPopup-TroubleTicketsTransactionsScreen-_msgs');
	troubleTicketTransactionsPopup_Paging = PcfButton('#TroubleTicketTransactionsPopup-_Paging');
	troubleTicketTransactionsPopup__crumb__ = PcfComponent('#TroubleTicketTransactionsPopup-__crumb__');
}
