import { PcfComponent } from '@gtui/gt-ui-framework';

export class CommercialPackageAcceleratedMenuActions {
	commercialPropertyCommercialPropertyLinks_CommercialProperty_BuildingsAndLocations = PcfComponent('#PolicyFile-PolicyFileAcceleratedMenuActions-PolicyMenuItemSet-CommercialProperty-CommercialPropertyLinks_CommercialProperty_BuildingsAndLocations');
	commercialPropertyCommercialPropertyLinks_CommercialProperty_Modifiers = PcfComponent('#PolicyFile-PolicyFileAcceleratedMenuActions-PolicyMenuItemSet-CommercialProperty-CommercialPropertyLinks_CommercialProperty_Modifiers');
	policyMenuItemSetCommercialProperty = PcfComponent('#PolicyFile-PolicyFileAcceleratedMenuActions-PolicyMenuItemSet-CommercialProperty');
	generalLiabilityGeneralLiabilityLinks_GeneralLiability_Coverages_GL = PcfComponent('#PolicyFile-PolicyFileAcceleratedMenuActions-PolicyMenuItemSet-GeneralLiability-GeneralLiabilityLinks_GeneralLiability_Coverages_GL');
	generalLiabilityGeneralLiabilityLinks_GeneralLiability_ExposureUnits_GL = PcfComponent('#PolicyFile-PolicyFileAcceleratedMenuActions-PolicyMenuItemSet-GeneralLiability-GeneralLiabilityLinks_GeneralLiability_ExposureUnits_GL');
	generalLiabilityGeneralLiabilityLinks_GeneralLiability_Modifiers_GL = PcfComponent('#PolicyFile-PolicyFileAcceleratedMenuActions-PolicyMenuItemSet-GeneralLiability-GeneralLiabilityLinks_GeneralLiability_Modifiers_GL');
	policyMenuItemSetGeneralLiability = PcfComponent('#PolicyFile-PolicyFileAcceleratedMenuActions-PolicyMenuItemSet-GeneralLiability');
	policyMenuItemSetInlandMarine = PcfComponent('#PolicyFile-PolicyFileAcceleratedMenuActions-PolicyMenuItemSet-InlandMarine');
	inlandMarineInlandMarineLinks_InlandMarine_BuildingsAndLocations = PcfComponent('#PolicyFile-PolicyFileAcceleratedMenuActions-PolicyMenuItemSet-InlandMarine-InlandMarineLinks_InlandMarine_BuildingsAndLocations');
	policyFilePolicyFileAcceleratedMenuActionsPolicyMenuItemSetPolicyMenuItemSet_Endorsements = PcfComponent('#PolicyFile-PolicyFileAcceleratedMenuActions-PolicyMenuItemSet-PolicyMenuItemSet_Endorsements');
	policyFilePolicyFileAcceleratedMenuActionsPolicyMenuItemSetPolicyMenuItemSet_Locations = PcfComponent('#PolicyFile-PolicyFileAcceleratedMenuActions-PolicyMenuItemSet-PolicyMenuItemSet_Locations');
	policyFilePolicyFileAcceleratedMenuActionsPolicyMenuItemSetPolicyMenuItemSet_Modifiers = PcfComponent('#PolicyFile-PolicyFileAcceleratedMenuActions-PolicyMenuItemSet-PolicyMenuItemSet_Modifiers');
	policyFilePolicyFileAcceleratedMenuActionsPolicyMenuItemSetPolicyMenuItemSet_PolicyInfo = PcfComponent('#PolicyFile-PolicyFileAcceleratedMenuActions-PolicyMenuItemSet-PolicyMenuItemSet_PolicyInfo');
	policyFilePolicyFileAcceleratedMenuActionsPolicyMenuItemSetPolicyMenuItemSet_Pricing = PcfComponent('#PolicyFile-PolicyFileAcceleratedMenuActions-PolicyMenuItemSet-PolicyMenuItemSet_Pricing');
	policyMenuItemSet_CommercialPackagegetId = PcfComponent('#PolicyMenuItemSet_CommercialPackage.getId()');
}
