import { PcfComponent } from '@gtui/gt-ui-framework';
import { PcfTextInput } from '@gtui/gt-ui-framework';
import { PcfDateValueInput } from '@gtui/gt-ui-framework';
import { PcfSelectInput } from '@gtui/gt-ui-framework';
import { PcfButton } from '@gtui/gt-ui-framework';
import { PcfListView } from '@gtui/gt-ui-framework';
import { PcfCheckBox } from '@gtui/gt-ui-framework';

export class CPBuildingPopup {
	cPBuildingPopupAdditionalCoveragesPanelSetAdditionalCoveragesDV_tbAdd = PcfButton('#CPBuildingPopup-AdditionalCoveragesPanelSet-AdditionalCoveragesDV_tb-Add');
	cPBuildingPopupAdditionalInterestDetailsDVAdditionalInterestLV = PcfListView('#CPBuildingPopup-AdditionalInterestDetailsDV-AdditionalInterestLV');
	cPBuildingPopupAdditionalInterestDetailsDVAdditionalInterestLV_tbAdd = PcfButton('#CPBuildingPopup-AdditionalInterestDetailsDV-AdditionalInterestLV_tb-Add');
	cPBuildingPopupAdditionalInterestDetailsDVAdditionalInterestLV_tbAddContactsButton = PcfButton('#CPBuildingPopup-AdditionalInterestDetailsDV-AdditionalInterestLV_tb-AddContactsButton');
	cPBuildingPopupAdditionalInterestDetailsDVAdditionalInterestLV_tbAddContactsButtonAddExistingContact = PcfButton('#CPBuildingPopup-AdditionalInterestDetailsDV-AdditionalInterestLV_tb-AddContactsButton-AddExistingContact');
	cPBuildingPopupAdditionalInterestDetailsDVAdditionalInterestLV_tbAddContactsButtonAddFromSearch = PcfButton('#CPBuildingPopup-AdditionalInterestDetailsDV-AdditionalInterestLV_tb-AddContactsButton-AddFromSearch');
	cPBuildingPopupAdditionalInterestDetailsDVAdditionalInterestLV_tbAddContactsButtonAddOtherContact = PcfButton('#CPBuildingPopup-AdditionalInterestDetailsDV-AdditionalInterestLV_tb-AddContactsButton-AddOtherContact');
	cPBuildingPopupAdditionalInterestDetailsDVAdditionalInterestLV_tbRemove = PcfButton('#CPBuildingPopup-AdditionalInterestDetailsDV-AdditionalInterestLV_tb-Remove');
	cPBuildingPopupBuildingAddlInterestTab = PcfButton('#CPBuildingPopup-BuildingAddlInterestTab');
	cPBuildingPopupBuildingCoveragesTab = PcfButton('#CPBuildingPopup-BuildingCoveragesTab');
	cPBuildingPopupBuildingDetailsTab = PcfButton('#CPBuildingPopup-BuildingDetailsTab');
	cPBuildingPopupCPBuildingPopup_UpLink = PcfButton('#CPBuildingPopup-CPBuildingPopup_UpLink');
	cPBuildingPopupCancel = PcfButton('#CPBuildingPopup-Cancel');
	alarmInfoInputGroupAlarmCertificate = PcfTextInput('#CPBuildingPopup-DetailsDV-AlarmInfoInputGroup-AlarmCertificate');
	alarmInfoInputGroupAlarmClass = PcfSelectInput('#CPBuildingPopup-DetailsDV-AlarmInfoInputGroup-AlarmClass');
	alarmInfoInputGroupAlarmExpiration = PcfDateValueInput('#CPBuildingPopup-DetailsDV-AlarmInfoInputGroup-AlarmExpiration');
	alarmInfoInputGroupAlarmGrade = PcfSelectInput('#CPBuildingPopup-DetailsDV-AlarmInfoInputGroup-AlarmGrade');
	alarmInfoInputGroupAlarmType = PcfSelectInput('#CPBuildingPopup-DetailsDV-AlarmInfoInputGroup-AlarmType');
	alarmInfoInputGroup_checkbox = PcfCheckBox('#CPBuildingPopup-DetailsDV-AlarmInfoInputGroup-_checkbox');
	detailsDVBasementArea = PcfTextInput('#CPBuildingPopup-DetailsDV-BasementArea');
	detailsDVBuildingLocation = PcfSelectInput('#CPBuildingPopup-DetailsDV-BuildingLocation');
	detailsDVBuildingNumber = PcfTextInput('#CPBuildingPopup-DetailsDV-BuildingNumber');
	detailsDVBurglarySafeguard = PcfSelectInput('#CPBuildingPopup-DetailsDV-BurglarySafeguard');
	cPBuildingPopupDetailsDVClassCodeSelectClassCode = PcfButton('#CPBuildingPopup-DetailsDV-ClassCode-SelectClassCode');
	detailsDVClassDescription = PcfTextInput('#CPBuildingPopup-DetailsDV-ClassDescription');
	detailsDVConstructionType = PcfSelectInput('#CPBuildingPopup-DetailsDV-ConstructionType');
	detailsDVCoverageForm = PcfSelectInput('#CPBuildingPopup-DetailsDV-CoverageForm');
	detailsDVDescription = PcfTextInput('#CPBuildingPopup-DetailsDV-Description');
	detailsDVFrontExposure = PcfTextInput('#CPBuildingPopup-DetailsDV-FrontExposure');
	detailsDVHeatingBoilerElsewhere = PcfComponent('#CPBuildingPopup-DetailsDV-HeatingBoilerElsewhere');
	detailsDVHeatingBoilerOnPremises = PcfComponent('#CPBuildingPopup-DetailsDV-HeatingBoilerOnPremises');
	detailsDVInterestType = PcfSelectInput('#CPBuildingPopup-DetailsDV-InterestType');
	detailsDVLastUpdateHeating = PcfTextInput('#CPBuildingPopup-DetailsDV-LastUpdateHeating');
	detailsDVLastUpdatePlumbing = PcfTextInput('#CPBuildingPopup-DetailsDV-LastUpdatePlumbing');
	detailsDVLastUpdateRoofing = PcfTextInput('#CPBuildingPopup-DetailsDV-LastUpdateRoofing');
	detailsDVLastUpdateWiring = PcfTextInput('#CPBuildingPopup-DetailsDV-LastUpdateWiring');
	detailsDVLeftExposure = PcfTextInput('#CPBuildingPopup-DetailsDV-LeftExposure');
	detailsDVNumBasements = PcfTextInput('#CPBuildingPopup-DetailsDV-NumBasements');
	detailsDVNumStories = PcfTextInput('#CPBuildingPopup-DetailsDV-NumStories');
	detailsDVPercentSprinklered = PcfSelectInput('#CPBuildingPopup-DetailsDV-PercentSprinklered');
	detailsDVPercentVacant = PcfSelectInput('#CPBuildingPopup-DetailsDV-PercentVacant');
	detailsDVRateType = PcfSelectInput('#CPBuildingPopup-DetailsDV-RateType');
	detailsDVRearExposure = PcfTextInput('#CPBuildingPopup-DetailsDV-RearExposure');
	detailsDVRentedOthers = PcfSelectInput('#CPBuildingPopup-DetailsDV-RentedOthers');
	detailsDVRightExposure = PcfTextInput('#CPBuildingPopup-DetailsDV-RightExposure');
	detailsDVRoofType = PcfSelectInput('#CPBuildingPopup-DetailsDV-RoofType');
	detailsDVTotalArea = PcfTextInput('#CPBuildingPopup-DetailsDV-TotalArea');
	detailsDVWindRating = PcfSelectInput('#CPBuildingPopup-DetailsDV-WindRating');
	detailsDVYearBuilt = PcfTextInput('#CPBuildingPopup-DetailsDV-YearBuilt');
	cPBuildingPopupEdit = PcfButton('#CPBuildingPopup-Edit');
	cPBuildingPopupEditPolicyButton = PcfButton('#CPBuildingPopup-EditPolicyButton');
	cPBuildingPopupPreferredCoverageCurrencySelectorRefPreferredCoverageCurrencyPanelSetCoverageCurrencyDisplay = PcfTextInput('#CPBuildingPopup-PreferredCoverageCurrencySelectorRef-PreferredCoverageCurrencyPanelSet-CoverageCurrencyDisplay');
	cPBuildingPopupPreferredCoverageCurrencySelectorRefPreferredCoverageCurrencyPanelSetPreferredCoverageCurrencySelectorDropDown = PcfSelectInput('#CPBuildingPopup-PreferredCoverageCurrencySelectorRef-PreferredCoverageCurrencyPanelSet-PreferredCoverageCurrencySelectorDropDown');
	cPBuildingPopupUpdate = PcfButton('#CPBuildingPopup-Update');
	cPBuildingPopup_Paging = PcfButton('#CPBuildingPopup-_Paging');
	cPBuildingPopup__crumb__ = PcfComponent('#CPBuildingPopup-__crumb__');
	cPBuildingPopup_msgs = PcfButton('#CPBuildingPopup-_msgs');
}
